**Necessary Imports**

execute the following line in environment "pip install torch==1.4.0 torchvision==0.5.0"

In [1]:
import torch
import torchvision
print(f"Torch version: {torch.__version__}\nTorchvision version: {torchvision.__version__}\n")

Torch version: 1.4.0
Torchvision version: 0.5.0



**Creating a tensor object**

In [2]:
a_tensor = torch.tensor([[1,2,3], [4,5,6]]) #tensor like numpy array
print(a_tensor,"\n")
print(a_tensor.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) 

torch.Size([2, 3])


In [3]:
b = a_tensor[:,:2]
b[0,:] = 0
print(b) 
print(a_tensor)
# b points the same memory location as a_tensor

tensor([[0, 0],
        [4, 5]])
tensor([[0, 0, 3],
        [4, 5, 6]])


**Mathematical operations**

In [4]:
print(a_tensor[a_tensor>1])

x = torch.tensor([[1,2], [3,4]])
y = torch.tensor([[5,6], [7,8]])

#elementwise ops
print(x+y)
print(x-y)
print(x*y)

tensor([3, 4, 5, 6])
tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])


Default is floor division. If you want true divison for integers, first convert integers to floats or use the format:'torch.div(a,b,out=c)'

In [5]:
print(x/y)

result = torch.empty(x.shape)
torch.div(x,y, out = result)
print(result)

tensor([[0, 0],
        [0, 0]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


**Devices**

While training the network all tensors should be on the same device. Tensors can be moved with '.to' method

In [6]:
#Use 'torch.device' objects to move tensors in and out of GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

print(f"Original device: {x.device}") # "cpu", integer

tensor = x.to(device)
print(f"Current device: {x.device}") #"cpu" or "cuda", double

cpu
Original device: cpu
Current device: cpu
